# Generated by Django 2.0.2 on 2018-02-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20180205_2328'),
        ('productsapp', '0003_product_image'),
    ]

    operations = [
    ]
