# Generated by Django 2.0.2 on 2018-02-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_merge_20180206_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='productsapp/photos', verbose_name='Фото'),
        ),
    ]
