# Generated by Django 2.0.2 on 2018-02-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_auto_20180207_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='productsapp_images/', verbose_name='Фото'),
        ),
    ]
